-- OCR 系统：空库一键初始化（MySQL 8+）

CREATE DATABASE IF NOT EXISTS ocr_system
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE ocr_system;

-- OCR 任务表（每条 task 对应已落盘的单页 PDF 或单张图片）
CREATE TABLE IF NOT EXISTS ocr_task (
    id INT AUTO_INCREMENT PRIMARY KEY,
    stored_file_name VARCHAR(255) NOT NULL COMMENT '落盘文件名',
    file_path VARCHAR(1024) NOT NULL COMMENT '本地文件路径',
    file_type VARCHAR(32) NOT NULL COMMENT 'pdf/png/jpg/jpeg/webp',
    file_size BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'uploaded' COMMENT 'processing/success/failed',
    error_message TEXT,
    ocr_elapsed_ms INT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '任务提交时间',
    INDEX idx_file_type (file_type),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OCR 任务表';

-- OCR 结果表（一 task 一 result）
CREATE TABLE IF NOT EXISTS ocr_result (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    markdown_content TEXT NOT NULL,
    verified_markdown TEXT NULL COMMENT '用户校对并通过后保存的渲染稿（HTML 片段）',
    is_verified TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 未验证，1 已验证',
    INDEX idx_task_id (task_id),
    INDEX idx_is_verified (is_verified),
    FOREIGN KEY (task_id) REFERENCES ocr_task(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OCR 结果表';

CREATE TABLE IF NOT EXISTS board_chongya_duanya (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    ocr_result_id INT NOT NULL,
    key_name VARCHAR(16) NOT NULL,
    production_date DATE NOT NULL,
    shift VARCHAR(16) NULL,
    product_name VARCHAR(64) NULL,
    process_name VARCHAR(32) NOT NULL,
    batch_1 VARCHAR(64) NULL,
    batch_2 VARCHAR(64) NULL,
    batch_3 VARCHAR(64) NULL,
    batch_4 VARCHAR(64) NULL,
    line_1 VARCHAR(64) NULL,
    line_2 VARCHAR(64) NULL,
    line_3 VARCHAR(64) NULL,
    line_4 VARCHAR(64) NULL,
    input_1 VARCHAR(64) NULL,
    input_2 VARCHAR(64) NULL,
    input_3 VARCHAR(64) NULL,
    input_4 VARCHAR(64) NULL,
    input_total VARCHAR(64) NULL,
    good_1 INT NULL,
    good_2 INT NULL,
    good_3 INT NULL,
    good_4 INT NULL,
    good_total INT NULL,
    bad_1 INT NULL,
    bad_2 INT NULL,
    bad_3 INT NULL,
    bad_4 INT NULL,
    bad_total INT NULL,
    actual_yield_1 DECIMAL(5,2) NULL,
    actual_yield_2 DECIMAL(5,2) NULL,
    actual_yield_3 DECIMAL(5,2) NULL,
    actual_yield_4 DECIMAL(5,2) NULL,
    actual_yield_total DECIMAL(5,2) NULL,
    target_yield_1 DECIMAL(5,2) NULL,
    target_yield_2 DECIMAL(5,2) NULL,
    target_yield_3 DECIMAL(5,2) NULL,
    target_yield_4 DECIMAL(5,2) NULL,
    target_yield_total DECIMAL(5,2) NULL,
    -- 5.0+1.0/-0.3 偏小
    `_5_0_1_0_0_3_pian_xiao_badnum_1` INT,
    `_5_0_1_0_0_3_pian_xiao_badnum_2` INT,
    `_5_0_1_0_0_3_pian_xiao_badnum_3` INT,
    `_5_0_1_0_0_3_pian_xiao_badnum_4` INT,
    `_5_0_1_0_0_3_pian_xiao_badnum_total` INT,
    `_5_0_1_0_0_3_pian_xiao_badrate_1` DECIMAL(5,2),
    `_5_0_1_0_0_3_pian_xiao_badrate_2` DECIMAL(5,2),
    `_5_0_1_0_0_3_pian_xiao_badrate_3` DECIMAL(5,2),
    `_5_0_1_0_0_3_pian_xiao_badrate_4` DECIMAL(5,2),
    `_5_0_1_0_0_3_pian_xiao_badrate_total` DECIMAL(5,2),
    -- 50+12/-3 偏小
    `_50_12_3_pian_xiao_badnum_1` INT,
    `_50_12_3_pian_xiao_badnum_2` INT,
    `_50_12_3_pian_xiao_badnum_3` INT,
    `_50_12_3_pian_xiao_badnum_4` INT,
    `_50_12_3_pian_xiao_badnum_total` INT,
    `_50_12_3_pian_xiao_badrate_1` DECIMAL(5,2),
    `_50_12_3_pian_xiao_badrate_2` DECIMAL(5,2),
    `_50_12_3_pian_xiao_badrate_3` DECIMAL(5,2),
    `_50_12_3_pian_xiao_badrate_4` DECIMAL(5,2),
    `_50_12_3_pian_xiao_badrate_total` DECIMAL(5,2),
    -- 50+12/-3 偏大
    `_50_12_3_pian_da_badnum_1` INT,
    `_50_12_3_pian_da_badnum_2` INT,
    `_50_12_3_pian_da_badnum_3` INT,
    `_50_12_3_pian_da_badnum_4` INT,
    `_50_12_3_pian_da_badnum_total` INT,
    `_50_12_3_pian_da_badrate_1` DECIMAL(5,2),
    `_50_12_3_pian_da_badrate_2` DECIMAL(5,2),
    `_50_12_3_pian_da_badrate_3` DECIMAL(5,2),
    `_50_12_3_pian_da_badrate_4` DECIMAL(5,2),
    `_50_12_3_pian_da_badrate_total` DECIMAL(5,2),
    -- 垂直度 0.40 偏大
    `chui_zhi_du_0_40_pian_da_badnum_1` INT,
    `chui_zhi_du_0_40_pian_da_badnum_2` INT,
    `chui_zhi_du_0_40_pian_da_badnum_3` INT,
    `chui_zhi_du_0_40_pian_da_badnum_4` INT,
    `chui_zhi_du_0_40_pian_da_badnum_total` INT,
    `chui_zhi_du_0_40_pian_da_badrate_1` DECIMAL(5,2),
    `chui_zhi_du_0_40_pian_da_badrate_2` DECIMAL(5,2),
    `chui_zhi_du_0_40_pian_da_badrate_3` DECIMAL(5,2),
    `chui_zhi_du_0_40_pian_da_badrate_4` DECIMAL(5,2),
    `chui_zhi_du_0_40_pian_da_badrate_total` DECIMAL(5,2),
    -- 垂直度 0.70 偏大
    `chui_zhi_du_0_70_pian_da_badnum_1` INT,
    `chui_zhi_du_0_70_pian_da_badnum_2` INT,
    `chui_zhi_du_0_70_pian_da_badnum_3` INT,
    `chui_zhi_du_0_70_pian_da_badnum_4` INT,
    `chui_zhi_du_0_70_pian_da_badnum_total` INT,
    `chui_zhi_du_0_70_pian_da_badrate_1` DECIMAL(5,2),
    `chui_zhi_du_0_70_pian_da_badrate_2` DECIMAL(5,2),
    `chui_zhi_du_0_70_pian_da_badrate_3` DECIMAL(5,2),
    `chui_zhi_du_0_70_pian_da_badrate_4` DECIMAL(5,2),
    `chui_zhi_du_0_70_pian_da_badrate_total` DECIMAL(5,2),
    -- 4.20+/-0.30∣P1-P3∣＜0.2 偏大
    `_4_20_0_30_P1_P3_0_2_pian_da_badnum_1` INT,
    `_4_20_0_30_P1_P3_0_2_pian_da_badnum_2` INT,
    `_4_20_0_30_P1_P3_0_2_pian_da_badnum_3` INT,
    `_4_20_0_30_P1_P3_0_2_pian_da_badnum_4` INT,
    `_4_20_0_30_P1_P3_0_2_pian_da_badnum_total` INT,
    `_4_20_0_30_P1_P3_0_2_pian_da_badrate_1` DECIMAL(5,2),
    `_4_20_0_30_P1_P3_0_2_pian_da_badrate_2` DECIMAL(5,2),
    `_4_20_0_30_P1_P3_0_2_pian_da_badrate_3` DECIMAL(5,2),
    `_4_20_0_30_P1_P3_0_2_pian_da_badrate_4` DECIMAL(5,2),
    `_4_20_0_30_P1_P3_0_2_pian_da_badrate_total` DECIMAL(5,2),
    -- 4.20+/-0.30∣P2-P4∣＜0.2 偏大
    `_4_20_0_30_P2_P4_0_2_pian_da_badnum_1` INT,
    `_4_20_0_30_P2_P4_0_2_pian_da_badnum_2` INT,
    `_4_20_0_30_P2_P4_0_2_pian_da_badnum_3` INT,
    `_4_20_0_30_P2_P4_0_2_pian_da_badnum_4` INT,
    `_4_20_0_30_P2_P4_0_2_pian_da_badnum_total` INT,
    `_4_20_0_30_P2_P4_0_2_pian_da_badrate_1` DECIMAL(5,2),
    `_4_20_0_30_P2_P4_0_2_pian_da_badrate_2` DECIMAL(5,2),
    `_4_20_0_30_P2_P4_0_2_pian_da_badrate_3` DECIMAL(5,2),
    `_4_20_0_30_P2_P4_0_2_pian_da_badrate_4` DECIMAL(5,2),
    `_4_20_0_30_P2_P4_0_2_pian_da_badrate_total` DECIMAL(5,2),
    -- 2D 碼偏位
    `_2D_ma_pian_wei_badnum_1` INT,
    `_2D_ma_pian_wei_badnum_2` INT,
    `_2D_ma_pian_wei_badnum_3` INT,
    `_2D_ma_pian_wei_badnum_4` INT,
    `_2D_ma_pian_wei_badnum_total` INT,
    `_2D_ma_pian_wei_badrate_1` DECIMAL(5,2),
    `_2D_ma_pian_wei_badrate_2` DECIMAL(5,2),
    `_2D_ma_pian_wei_badrate_3` DECIMAL(5,2),
    `_2D_ma_pian_wei_badrate_4` DECIMAL(5,2),
    `_2D_ma_pian_wei_badrate_total` DECIMAL(5,2),
    -- DDS
    `DDS_badnum_1` INT,
    `DDS_badnum_2` INT,
    `DDS_badnum_3` INT,
    `DDS_badnum_4` INT,
    `DDS_badnum_total` INT,
    `DDS_badrate_1` DECIMAL(5,2),
    `DDS_badrate_2` DECIMAL(5,2),
    `DDS_badrate_3` DECIMAL(5,2),
    `DDS_badrate_4` DECIMAL(5,2),
    `DDS_badrate_total` DECIMAL(5,2),
    INDEX idx_board_chongya_duanya_date (production_date),
    INDEX idx_board_chongya_duanya_process (process_name),
    INDEX idx_board_chongya_duanya_product (product_name),
    UNIQUE KEY uq_board_chongya_duanya_biz (production_date, shift),
    FOREIGN KEY (task_id) REFERENCES ocr_task(id) ON DELETE CASCADE,
    FOREIGN KEY (ocr_result_id) REFERENCES ocr_result(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据看板-冲压-锻压';

CREATE TABLE IF NOT EXISTS board_chongya_gurong (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    ocr_result_id INT NOT NULL,
    key_name VARCHAR(16) NOT NULL,
    production_date DATE NOT NULL,
    shift VARCHAR(16) NULL,
    product_name VARCHAR(64) NULL,
    process_name VARCHAR(32) NOT NULL,
    line_1 VARCHAR(64) NULL,
    line_2 VARCHAR(64) NULL,
    line_3 VARCHAR(64) NULL,
    input_1 INT NULL,
    input_2 INT NULL,
    input_3 INT NULL,
    input_total INT NULL,
    good_1 INT NULL,
    good_2 INT NULL,
    good_3 INT NULL,
    good_total INT NULL,
    bad_1 INT NULL,
    bad_2 INT NULL,
    bad_3 INT NULL,
    bad_total INT NULL,
    actual_yield_1 DECIMAL(5,2) NULL,
    actual_yield_2 DECIMAL(5,2) NULL,
    actual_yield_3 DECIMAL(5,2) NULL,
    actual_yield_total DECIMAL(5,2) NULL,
    target_yield_1 DECIMAL(5,2) NULL,
    target_yield_2 DECIMAL(5,2) NULL,
    target_yield_3 DECIMAL(5,2) NULL,
    target_yield_total DECIMAL(5,2) NULL,
    -- 硬度 40≤Hba≤60 偏大
    `ying_du_40_Hba_60_pian_da_badnum_1` INT,
    `ying_du_40_Hba_60_pian_da_badnum_2` INT,
    `ying_du_40_Hba_60_pian_da_badnum_3` INT,
    `ying_du_40_Hba_60_pian_da_badnum_total` INT,
    `ying_du_40_Hba_60_pian_da_badrate_1` DECIMAL(5,2),
    `ying_du_40_Hba_60_pian_da_badrate_2` DECIMAL(5,2),
    `ying_du_40_Hba_60_pian_da_badrate_3` DECIMAL(5,2),
    `ying_du_40_Hba_60_pian_da_badrate_total` DECIMAL(5,2),
    -- 變形
    `bian_xing_badnum_1` INT,
    `bian_xing_badnum_2` INT,
    `bian_xing_badnum_3` INT,
    `bian_xing_badnum_total` INT,
    `bian_xing_badrate_1` DECIMAL(5,2),
    `bian_xing_badrate_2` DECIMAL(5,2),
    `bian_xing_badrate_3` DECIMAL(5,2),
    `bian_xing_badrate_total` DECIMAL(5,2),
    -- DDS
    `DDS_badnum_1` INT,
    `DDS_badnum_2` INT,
    `DDS_badnum_3` INT,
    `DDS_badnum_total` INT,
    `DDS_badrate_1` DECIMAL(5,2),
    `DDS_badrate_2` DECIMAL(5,2),
    `DDS_badrate_3` DECIMAL(5,2),
    `DDS_badrate_total` DECIMAL(5,2),
    INDEX idx_board_chongya_gurong_date (production_date),
    INDEX idx_board_chongya_gurong_process (process_name),
    INDEX idx_board_chongya_gurong_product (product_name),
    UNIQUE KEY uq_board_chongya_gurong_biz (production_date, shift),
    FOREIGN KEY (task_id) REFERENCES ocr_task(id) ON DELETE CASCADE,
    FOREIGN KEY (ocr_result_id) REFERENCES ocr_result(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据看板-冲压-固熔（三线体+汇总，无批次）';

CREATE TABLE IF NOT EXISTS board_chongya_shixiao (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    ocr_result_id INT NOT NULL,
    key_name VARCHAR(16) NOT NULL,
    production_date DATE NOT NULL,
    shift VARCHAR(16) NULL,
    product_name VARCHAR(64) NULL,
    process_name VARCHAR(32) NOT NULL,
    input INT NULL,
    good INT NULL,
    bad INT NULL,
    actual_yield DECIMAL(5,2) NULL,
    target_yield DECIMAL(5,2) NULL,
    -- 變形
    `bian_xing_badnum_total` INT,
    `bian_xing_badrate_total` DECIMAL(5,2),
    -- 機械性能送檢
    `ji_xie_xing_neng_song_jian_badnum_total` INT,
    `ji_xie_xing_neng_song_jian_badrate_total` DECIMAL(5,2),
    -- 硬度 Hba≥74 偏小
    `ying_du_Hba_74_pian_xiao_badnum_total` INT,
    `ying_du_Hba_74_pian_xiao_badrate_total` DECIMAL(5,2),
    -- DDS
    `DDS_badnum_total` INT,
    `DDS_badrate_total` DECIMAL(5,2),
    INDEX idx_board_chongya_shixiao_date (production_date),
    INDEX idx_board_chongya_shixiao_process (process_name),
    INDEX idx_board_chongya_shixiao_product (product_name),
    UNIQUE KEY uq_board_chongya_shixiao_biz (production_date, shift),
    FOREIGN KEY (task_id) REFERENCES ocr_task(id) ON DELETE CASCADE,
    FOREIGN KEY (ocr_result_id) REFERENCES ocr_result(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据看板-冲压-时效';

CREATE TABLE IF NOT EXISTS board_jinjia_cnc0 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    ocr_result_id INT NOT NULL,
    key_name VARCHAR(16) NOT NULL,
    production_date DATE NOT NULL,
    shift VARCHAR(16) NULL,
    product_name VARCHAR(64) NULL,
    process_name VARCHAR(32) NOT NULL,
    inspection_location VARCHAR(32) NULL,
    input INT NULL,
    sample INT NULL,
    first_good INT NULL,
    bad_count INT NULL,
    reworkable_bad INT NULL,
    unreworkable_bad INT NULL,
    first_yield DECIMAL(5,2) NULL,
    second_yield DECIMAL(5,2) NULL,
    first_target_yield DECIMAL(5,2) NULL,
    second_target_yield DECIMAL(5,2) NULL,
    -- DDS
    `DDS_badnum_reworkable` INT,
    `DDS_badnum_unreworkable` INT,
    `DDS_badrate_total` DECIMAL(5,2),
    -- 臺階/過切
    `tai_jie_guo_qie_badnum_reworkable` INT,
    `tai_jie_guo_qie_badnum_unreworkable` INT,
    `tai_jie_guo_qie_badrate_total` DECIMAL(5,2),
    -- 毛邊/毛刺
    `mao_bian_mao_ci_badnum_reworkable` INT,
    `mao_bian_mao_ci_badnum_unreworkable` INT,
    `mao_bian_mao_ci_badrate_total` DECIMAL(5,2),
    -- 大平面未見光
    `da_ping_mian_wei_jian_guang_badnum_reworkable` INT,
    `da_ping_mian_wei_jian_guang_badnum_unreworkable` INT,
    `da_ping_mian_wei_jian_guang_badrate_total` DECIMAL(5,2),
    -- 大平面刀紋/刀痕
    `da_ping_mian_dao_wen_dao_hen_badnum_reworkable` INT,
    `da_ping_mian_dao_wen_dao_hen_badnum_unreworkable` INT,
    `da_ping_mian_dao_wen_dao_hen_badrate_total` DECIMAL(5,2),
    -- 平面度 0.10 偏大
    `ping_mian_du_0_10_pian_da_badnum_reworkable` INT,
    `ping_mian_du_0_10_pian_da_badnum_unreworkable` INT,
    `ping_mian_du_0_10_pian_da_badrate_total` DECIMAL(5,2),
    -- 4.70+/-0.10 偏大
    `_4_70_0_10_pian_da_badnum_reworkable` INT,
    `_4_70_0_10_pian_da_badnum_unreworkable` INT,
    `_4_70_0_10_pian_da_badrate_total` DECIMAL(5,2),
    -- 4.70+/-0.10 偏小
    `_4_70_0_10_pian_xiao_badnum_reworkable` INT,
    `_4_70_0_10_pian_xiao_badnum_unreworkable` INT,
    `_4_70_0_10_pian_xiao_badrate_total` DECIMAL(5,2),
    INDEX idx_board_jinjia_cnc0_date (production_date),
    INDEX idx_board_jinjia_cnc0_process (process_name),
    INDEX idx_board_jinjia_cnc0_product (product_name),
    UNIQUE KEY uq_board_jinjia_cnc0_biz (production_date, shift, inspection_location),
    FOREIGN KEY (task_id) REFERENCES ocr_task(id) ON DELETE CASCADE,
    FOREIGN KEY (ocr_result_id) REFERENCES ocr_result(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据看板-金加-CNC0';

CREATE TABLE IF NOT EXISTS board_jinjia_cnc0_full (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_id INT NOT NULL,
    ocr_result_id INT NOT NULL,
    key_name VARCHAR(16) NOT NULL,
    production_date DATE NOT NULL,
    shift VARCHAR(16) NULL,
    product_name VARCHAR(64) NULL,
    process_name VARCHAR(32) NOT NULL,
    input INT NULL,
    first_good INT NULL,
    bad INT NULL,
    reworkable_bad INT NULL,
    unreworkable_bad INT NULL,
    first_yield DECIMAL(5,2) NULL COMMENT '一次良率',
    second_yield DECIMAL(5,2) NULL COMMENT '二次良率',
    first_target_yield DECIMAL(5,2) NULL COMMENT '一次目标良率',
    second_target_yield DECIMAL(5,2) NULL COMMENT '二次目标良率',
    -- 大平面刀紋/刀痕
    `da_ping_mian_dao_wen_dao_hen_badnum_total` INT,
    `da_ping_mian_dao_wen_dao_hen_badrate_total` DECIMAL(5,2),
    -- 毛邊/毛刺
    `mao_bian_mao_ci_badnum_total` INT,
    `mao_bian_mao_ci_badrate_total` DECIMAL(5,2),
    -- 大平面未見光
    `da_ping_mian_wei_jian_guang_badnum_total` INT,
    `da_ping_mian_wei_jian_guang_badrate_total` DECIMAL(5,2),
    INDEX idx_board_jinjia_cnc0_full_date (production_date),
    INDEX idx_board_jinjia_cnc0_full_process (process_name),
    INDEX idx_board_jinjia_cnc0_full_product (product_name),
    UNIQUE KEY uq_board_jinjia_cnc0_full_biz (production_date, shift),
    FOREIGN KEY (task_id) REFERENCES ocr_task(id) ON DELETE CASCADE,
    FOREIGN KEY (ocr_result_id) REFERENCES ocr_result(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据看板-金加-CNC0全检';
